### ISSUE TITLE
FUTURE: Ability to do "Existing Content" blocks

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#14]
Existing content blocks are something new to Backdrop core. They might have existed in contrib for Drupal, but I doubt this module supported them. 

Let's look into this possibility in the future - if users seem interested. 

If you are interested in this feature, comment here.

**Comment by jenlampton** [comment]
Embedding a fully rendered node (in any view mode) in filtered text on another node is problematic because it will create a race condition. The text is filtered as part of `node_load()`, so if node A embeds node B, and node B embeds node A, neither node will ever load properly. 

This issue will remain blocked until https://github.com/backdrop/backdrop-issues/issues/5642 is resolved.
