### ISSUE TITLE
MVP Upgrade Path: remove filter setting (only)

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#17]
We are not sure if we have time to deal with an upgrade path from Drupal 7 right now. Please, let us know if this is something you need.

**Comment by jenlampton** [comment]
For MVP, the upgrade path should remove the filter setting value for "Check the roles assigned by the block module", since the block module does not assign roles in Backdrop. 

As far as content that has embedded blocks, if we simply do not render unsupported block types (but leave them in the content) an upgrade path should not be necessary. The embedded blocks can wait there patiently until their block type is supported :)
