### ISSUE TITLE
Remove configuration options for block embed filter

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#21]
If you check the box on the filter configuration you get the error shown below.

![image](https://user-images.githubusercontent.com/3144571/154204697-ee7f9d87-05f5-4cf3-b0c2-87ecce3989d8.png)

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.block_role' doesn't exist: SELECT module, delta, rid FROM {block_role}; Array ( )`
![image](https://user-images.githubusercontent.com/3144571/154204918-4cabf51b-e2e8-46a3-ae8f-e1246c791bea.png)

**Comment by stpaultim** [comment]
We are no longer getting that error. I don't get any error if I enable this feature, but it also doesn't seem to do anything. I expect that blocks are handled differently enough in Backdrop, that this feature will need to be rewritten. 

Let's come back to this a little later.

**Comment by jenlampton** [comment]
The filter setting value for "Check the roles assigned by the block module" doesn't make sense anymore, since the block module does not assign roles in Backdrop. This configuration option needs to be removed entirely:

<img width="1221" alt="Screen Shot 2022-11-22 at 2 10 45 PM" src="https://user-images.githubusercontent.com/397895/203421851-64bc4d12-e73e-4e7c-8d78-5d296fc4e3ae.png">

**Comment by juanolalla** [comment]
Pull request to remove configuration options entirely: https://github.com/backdrop-contrib/ckeditor_blocks/pull/29

**Comment by jenlampton** [comment]
PR merged, closing :tada.
