### ISSUE TITLE
Remove Configuration Option for Entity Caching (replace with filter cache)

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#26]
To fix the problem in: https://github.com/backdrop-contrib/ckeditor_blocks/issues/25 we added code that always turns off entity caching on nodes. 

Maybe this should be an option that a site admin can enable or disable. It seems to be mostly only important for webform blocks. Other types of blocks may not need this. Since there are some performance implications, it might be best to allow the site admin to decide if this feature is enabled.

**Comment by jenlampton** [comment]
> To fix the problem in: https://github.com/backdrop-contrib/ckeditor_blocks/issues/25 we added code that always turns off entity caching on nodes.

A better solution to this problem is to mark any text format using this filter as non-cacheable, rather than disabling entity cache for all entities, regardless of whether the cache was problematic or not. 

Entity cache is a problematic solution for two reasons:

1) We're disabling caching in some places where we shouldn't be: Not all nodes will be using a text format that supports block rendering. 
2) We're not disabling cacheing in all places where we should be: text filters can appear in places other than entities, and we should disable caching in all those places too.

Entity cache is a separate thing that should never be used *only* for text filters.  It's most helpful when the properties of an entity changes from what's stored in the database. In this case, the node properties remain unchanged, it's only how (unchanged) text gets formatted that is an issue.

Please see the 'cache' element in [hook_filter_info()](https://docs.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.api.php/function/hook_filter_info/1)

**Comment by juanolalla** [comment]
Removed the piece of code which was disabling entity cache in #35, letting the cache disabled for the filter in hook_filter_info, which will disable cache for the whole text format using it.
